default-target-path: tmp
ucg-version: 1.0
properties:
  - name: baselib
    value: de.ollie.baselib
  - name: core-exception-package
    value: de.ollie.carp.vtt.core.service.exception
  - name: core-model-package
    value: de.ollie.carp.vtt.core.service.model
  - name: core-port-persistence-package
    value: de.ollie.carp.vtt.core.service.port.persistence
  - name: core-service-package
    value: de.ollie.carp.vtt.core.service
  - name: jpa-entity-package
    value: de.ollie.carp.vtt.persistence.jpa.dbo
  - name: jpa-mapper-package
    value: de.ollie.carp.vtt.persistence.jpa.mapper
  - name: jpa-repository-package
    value: de.ollie.carp.vtt.persistence.jpa.repository
  - name: shell-mapper-package
    value: de.ollie.carp.vtt.shell.mapper
  - name: swing-gui-package
    value: de.ollie.carp.vtt.gui.swing
generators:
# --- Service ---
  - type: CLASS
    package: de.ollie.carp.vtt.core.service.model
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    template: templates/core/Model.vc
    properties:
      - name: target-path
        value: service-interface/src/main/java
      - name: suppress-project-type-imports
        value: true
  - type: CLASS
    package: de.ollie.carp.vtt.core.service.port.persistence
    target-file-name: ${UnitName}PersistencePort
    path: generator
    template: templates/core/PersistencePort.vc
    properties:
      - name: target-path
        value: service-interface/src/main/java
# --- JPA ---
  - type: CLASS
    package: de.ollie.carp.vtt.persistence.jpa.dbo
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    target-file-name: ${UnitName}Dbo
    template: templates/persistence/jpa/Dbo.vc
    properties:
      - name: target-path
        value: jpa-persistence/src/main/java
  - type: CLASS
    package: de.ollie.carp.vtt.persistence.jpa.mapper
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    target-file-name: ${UnitName}DboMapper
    template: templates/persistence/jpa/DboMapper.vc
    properties:
      - name: target-path
        value: jpa-persistence/src/main/java
  - type: CLASS
    package: de.ollie.carp.vtt.persistence.jpa.repository
    target-file-name: ${UnitName}DboRepository
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    template: templates/persistence/jpa/DboRepository.vc
    properties:
      - name: target-path
        value: jpa-persistence/src/main/java
  - type: CLASS
    package: de.ollie.carp.vtt.persistence.jpa
    target-file-name: ${UnitName}JpaPersistenceAdapter
    path: generator
    template: templates/persistence/jpa/JpaPersistenceAdapter.vc
    properties:
      - name: target-path
        value: jpa-persistence/src/main/java